### ISSUE TITLE
Question: Why move to GitLab?

### ISSUE THREAD

**Issue by brillout** [rosarior/awesome-django#223]
Just out of curiosity:)

**Comment by AmineYaiche** [comment]
up

**Comment by metal-lady** [comment]
Because he is a homophobic, misogynist, gamergator that can't deal with Github's diversity and inclusion policies and needed to go hide in his safe space.
He is also the author of this monstrosity: https://github.com/rosarior/Code-of-Merit

**Comment by bittner** [comment]
`<off_topic>`
@metal-lady Who are you, spitting offending despiteful offences to people who help the Open Source community to grow? You're hiding behind a synonym, not disclosing neither your real face nor your real name, location or any other personal details.

It's because of people like you why projects need a code of conduct. Because of people that have a hard time respecting achievements, contributions, managerial measures with a positive attitude. You really want that this thread is also locked to avoid people like you from poisoning the climate of open collaboration. Please stop offending people.

Afterword
-------------
Be aware that in some countries it may be a criminal offence to claim people are what you called him (only "nazi" is missing in your list). When it proves unfounded, of course, what I'm certain of.
`</off_topic>`

**Comment by mikaelengstrom** [comment]
Since all other awesome-lists i have seen lives on git-hub, i think it makes sense to keep it here?

**Comment by bittner** [comment]
Interestingly, this is actually correct: The [entry for this list](https://github.com/sindresorhus/awesome#back-end-development) on "Awesome Lists" still points to the GitHub repo (not to the one on GitLab). For a reason?
